ALTER TABLE products
ADD COLUMN IF NOT EXISTS making_cost NUMERIC(12, 2) NOT NULL DEFAULT 0;

ALTER TABLE products
ADD COLUMN IF NOT EXISTS transaction_date DATE;

ALTER TABLE products
ADD COLUMN IF NOT EXISTS due_date DATE;
